### ISSUE TITLE
[dev] Checklist mise en place

### ISSUE THREAD

**Issue by statnmap** [spyrales/shinygouv#2]
- [x] Remplir les Key Dates et le calendrier prévisionnel
- [x] Ajouter chaque utilisateur au projet en tant que "Guest"
- [x] Prévenir les chefs de projets de monter le niveau de Notification à "Watch" sur la page d'acceuil du projet pour recevoir toutes les notifications
- [x] S'assurer que le Board est pret:https://github.com/spyrales/shinygouv/projects/1
- [x] S'assurer que le Wiki Home est pret:https://github.com/spyrales/shinygouv/wiki/Home
- [x] Indiquer aussi la méthode de partage de CR dans l'issue de Bienvenue du Client : https://github.com/spyrales/shinygouv/issues/1
- [x] Notifier chaque utilisateur en les mentionnant dans un commentaire de l'issue : https://github.com/spyrales/shinygouv/issues/1 avec le texte suivant : 
```
Merci de bien vouloir lire et valider le contenu de cette page.
Si vous lisez ce message dans un email, vous pouvez cliquer sur le lien suivant pour accéder à la page :
https://github.com/spyrales/shinygouv/issues/1
@mention, @mention, ...
```

- [ ] ~~Mettre en place {renv} en suivant "dev/dev_history_renv.R"~~
- [x] Si nécessaires, exécuter les étapes de "dev/dev_history.R". La plupart sont déja faites.
